heat_template_version: 2013-05-23

description: |
  Heat template to deploy a single server running a PHP app under apache

parameter_groups:

- label: Server Settings
  parameters:
  - image
  - flavor

- label: PHP Application Settings
  parameters:
  - url
  - revision
  - packages
  - repo
  - deploy_key
  - destination
  - public

- label: rax-dev-params
  parameters:
  - server_hostname
  - http_port
  - https_port
  - memcached_size
  - kitchen
  - chef_version

parameters:

  server_hostname:
    label: Server Name
    description: Server Name
    type: string
    default: php
    constraints:
    - length:
        min: 1
        max: 64
    - allowed_pattern: "^[a-zA-Z][a-zA-Z0-9-]*$"
      description: |
        Must begin with a letter and contain only alphanumeric characters.

  image:
    label: Operating System
    description: |
      Required: Server image used for all servers that are created as a part of
      this deployment.
    type: string
    default: Ubuntu 12.04 LTS (Precise Pangolin) (PVHVM)
    constraints:
    - allowed_values:
      - Ubuntu 12.04 LTS (Precise Pangolin) (PVHVM)
      description: Must be a supported operating system.

  flavor:
    label: Server Size
    description: |
      Required: Rackspace Cloud Server flavor to use. The size is based on the
      amount of RAM for the provisioned server.
    type: string
    default: 4 GB General Purpose v1
    constraints:
    - allowed_values:
      - 1 GB General Purpose v1
      - 2 GB General Purpose v1
      - 4 GB General Purpose v1
      - 8 GB General Purpose v1
      - 15 GB I/O v1
      - 30 GB I/O v1
      - 512MB Standard Instance
      - 1GB Standard Instance
      - 2GB Standard Instance
      - 4GB Standard Instance
      - 8GB Standard Instance
      - 15GB Standard Instance
      - 30GB Standard Instance
      description: |
        Must be a valid Rackspace Cloud Server flavor for the region you have
        selected to deploy into.

  revision:
    label: Revision
    description: |
      Optional: Git Branch/Ref to deploy. Default: HEAD
    type: string
    default: HEAD

  packages:
    label: System Packages
    description: |
      Optional: Additional system packages to install. For a list of available
      packages, see: http://packages.ubuntu.com/precise/allpackages
    type: string
    default: ''

  repo:
    label: Git Repository
    description: |
      Optional: URL to your git repository. Use the https syntax for public
      repositories, use git@ syntax for private repositories.
    type: string
    default: ''

  url:
    label: Site Domain
    description: URL for site
    type: string
    default: 'http://example.com'

  deploy_key:
    label: Git Deploy Key
    description: |
      Optional: If you specified a private repository, provide your private
      deploy key here.
    type: string
    default: ''

  destination:
    label: Site Path
    description: Path to setup your application on your servers.
    default: /var/www/vhosts/application
    type: string

  public:
    label: Public Directory
    description: |
      The public facing directory of your application relative to the
      destination.
    type: string
    default: /

  # sslcert:
  #  description: SSL Certificate
  #  type: string
  #  default: false

  # sslkey:
  #  description: SSL Key
  #  type: string
  #  default: false

  # sslcacert:
  #  description: SSL CA Certificate
  #  type: string
  #  default: false

  # varnish:
  #  description: Install Varnish
  #  type: string
  #  default: false

  http_port:
    label: HTTP Port
    description: HTTP Port
    type: string
    default: 80

  https_port:
    label: HTTPS Port
    description: HTTPS Port
    type: string
    default: 443

  memcached_size:
    label: Memcached Memory Limit
    description: Memcached memory size limit
    type: number
    default: 128

  kitchen:
    label: Kitchen
    description: URL for the kitchen to use
    type: string
    default: https://github.com/rackspace-orchestration-templates/php-app-single

  chef_version:
    label: Chef Version
    description: Version of chef client to use
    type: string
    default: 12.2.1-1

resources:

  ssh_key:
    type: "OS::Nova::KeyPair"
    properties:
      name: { get_param: "OS::stack_id" }
      save_private_key: true

  mysql_root_password:
    type: "OS::Heat::RandomString"
    properties:
      length: 32
      sequence: lettersdigits

  mysql_debian_password:
    type: "OS::Heat::RandomString"
    properties:
      length: 32
      sequence: lettersdigits

  php_server:
    type: "OS::Nova::Server"
    properties:
      name: { get_param: server_hostname }
      flavor: { get_param: flavor }
      image: { get_param: image }
      key_name: { get_resource: ssh_key }
      metadata:
        rax-heat: { get_param: "OS::stack_id" }

  php_setup:
    type: "OS::Heat::ChefSolo"
    depends_on: php_server
    properties:
      username: root
      private_key: { get_attr: [ssh_key, private_key] }
      host: { get_attr: [php_server, accessIPv4] }
      kitchen: { get_param: kitchen }
      chef_version: { get_param: chef_version }
      node:
        mysql:
          server_root_password: { get_attr: [mysql_root_password, value] }
          server_debian_password: { get_attr: [mysql_debian_password, value] }
          bind_address: 127.0.0.1
        php_app:
          destination: { get_param: destination }
          deploy_key: { get_param: deploy_key }
          http_port: { get_param: http_port }
          https_port: { get_param: https_port }
          packages: { get_param: packages }
          public: { get_param: public }
          repo: { get_param: repo }
          rev: { get_param: revision }
          # sslcert: { get_param: sslcert }
          # sslkey: { get_param: sslkey }
          # sslcacert: { get_param: sslcacert }
          url: { get_param: url }
          # varnish: { get_param: varnish }
        memcached:
          listen: 127.0.0.1
        varnish:
          backend_host: 127.0.0.1
        run_list: ["recipe[apt]",
                   "recipe[build-essential]",
                   "recipe[memcached]",
                   "recipe[rax_php_app]",
                   "recipe[php-ioncube]",
                   "recipe[mysql::server]"]


outputs:
  private_key:
    description: SSH Private Key
    value: { get_attr: [ssh_key, private_key] }

  server_ip:
    description: Server IP
    value: { get_attr: [php_server, accessIPv4] }

  mysql_root_password:
    description: MySQL Root Password
    value: { get_attr: [mysql_root_password, value] }
